package com.flowforge.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    UNAUTHENTICATED,
    INVALID_CREDENTIALS,
    NOT_FOUND,
    EMAIL_TAKEN,
    DUPLICATE_NAME,
    VERSION_CONFLICT,
    INVALID_STATE,
    PROJECT_NOT_EMPTY,
    STEP_LIMIT_REACHED,
    STEP_HAS_DEPENDENTS,
    DEPENDENCY_CYCLE,
    WORKFLOW_INVALID,
    INTERNAL_ERROR
}
